# need to run in the scripts/ directory

source("utils/utils_check_equal.m")
source("utils/utils_deg2rad.m")
source("utils/utils_rad2deg.m")
source("utils/utils_normalize.m")
source("utils/utils_solve_distance.m")
source("xform/xform_make_projection_matrix.m")
source("lin_interp/lin_interp_interpolate_line.m")
source("bar/bar_interpolate.m")
source("bar/bar_solve_bar_coords.m")
source("bezier/bezier_solve_pos_quadratic.m")
source("bezier/bezier_solve_pos_cubic.m")
source("bezier/bezier_solve_handles_cubic.m")
source("clip/clip_solve_plane_edge_intersection.m")
source("clip/clip_plot_triangle_in_ndc.m")
source("ray_trace/ray_trace_solve_intersection_sphere.m")
source("ray_trace/ray_trace_solve_intersection_plane.m")
source("ray_trace/ray_trace_solve_intersection_triangle.m")
source("ray_trace/ray_trace_solve_intersection_line.m")
source("ray_trace/ray_trace_solve_intersection_box2D.m")
source("ray_trace/ray_trace_solve_intersection_torus.m")
source("scatter/scatter_solve_refract_ray.m")
source("scatter/scatter_solve_reflect_ray.m")
source("frames/frames_solve_xform_matrix_VCS2WCS.m")

